AWSTemplateFormatVersion: "2010-09-09"
Description: provisions on-demand amazon linux bastion host valid for set interval
Parameters:
  pVpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC in which a bastion is needed
  pSubnetId:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Choose one public SubnetId to deploy bastion instance
  pSecurityGroupId:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: Choose a SecurityGroupId for remote bastion access
  pRequestorShortName:
    Type: String
    Description: Please supply your short username
    ConstraintDescription: "must be at least 5 characters"
    MinLength: 5
  pTargetInstanceId:
    Type: String
    Description: EC2 InstanceId of customer workload to create local account
  pBootstrapResources:
    Type: String
    Description: Name of S3 bucket containing EC2 bootstrap files (e.g., sshd_config)
    Default: insert_your_bucket_name
Mappings:
  RegionMap:
    us-east-1:
      "64": "ami-b73b63a0"
    us-west-1:
      "64": "ami-23e8a343"
    us-west-2:
      "64": "ami-5ec1673e"
Resources:
  RandomUserAndPwd:
    Type: Custom::RandomUserAndPwd
    Properties:
      ServiceToken: !Join ["", ["arn:aws:lambda:", !Ref "AWS::Region", ":", !Ref "AWS::AccountId", ":function:BastionRandomUserAndPwd"] ]
      Region: !Ref "AWS::Region"
      Requestor: !Ref pRequestorShortName
  CreateBastLocalAcct:
    Type: Custom::CreateBastLocalAcct
    Properties:
      ServiceToken: !Join ["", ["arn:aws:lambda:", !Ref "AWS::Region", ":", !Ref "AWS::AccountId", ":function:BastionCreateLocalAcct"] ]
      Region: !Ref "AWS::Region"
      random_username: !GetAtt RandomUserAndPwd.random_username
      random_pwd: !GetAtt RandomUserAndPwd.random_pwd
      request_user: !GetAtt RandomUserAndPwd.request_user
      expire_time: !GetAtt RandomUserAndPwd.expire_time
      instance_id: !Ref pTargetInstanceId
      platform: "linux"
    DependsOn: RandomUserAndPwd
  myBastionInstance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", 64]
      InstanceType: t2.micro
      SecurityGroupIds: !Ref pSecurityGroupId
      SubnetId: !Select [0, !Ref pSubnetId]
      KeyName: demo_gold
      Tags:
      - Key: Name
        Value: Bastion-Service
      - Key: bastion_flag
        Value: true
      - Key: expire_date_time
        Value: !GetAtt RandomUserAndPwd.expire_time
      UserData:
        "Fn::Base64":
          !Join ["", ["#!/bin/bash \n",
          "yum update -y \n",
          "curl https://s3.amazonaws.com/",
          !Ref pBootstrapResources,
          "/ssh/sshd_config -o /etc/ssh/sshd_config.v1 \n",
          "mv /etc/ssh/sshd_config.v1 /etc/ssh/sshd_config \n",
          "service sshd restart \n",
          "useradd -m -s /bin/bash ",
          !GetAtt RandomUserAndPwd.random_username,
          " \n",
          "echo ",
          !GetAtt RandomUserAndPwd.random_username,
          ":\"",
          !GetAtt RandomUserAndPwd.random_pwd,
          "\" | chpasswd \n" ] ]
Outputs:
  RandomUsername:
    Description: "random generated UserID for bastion instance"
    Value: !GetAtt RandomUserAndPwd.random_username
  RandomPwd:
    Description: "random generated pwd from lambda"
    Value: !GetAtt RandomUserAndPwd.random_pwd
  Requestor:
    Description: "support engineer requesting bastion access"
    Value: !GetAtt RandomUserAndPwd.request_user
  ExpireTime:
    Description: "date and time the bastion stack will expire"
    Value: !GetAtt RandomUserAndPwd.expire_time
  BastionPublicIP:
    Description: "public IP of bastion"
    Value: !GetAtt myBastionInstance.PublicIp
  BastionFlag:
    Description: "flag to indicate stack is a bastion stack monitored for expiration"
    Value: "true"
  BastionPlatform:
    Description: "Indicates windows or linux bastion for clean-up monitoring"
    Value: "linux"
  TargetInstanceId:
    Description: "InstanceId for target managed instance where local acct created"
    Value: !Ref pTargetInstanceId
